### ISSUE TITLE
Fix the code format in tables of case studies and blog posts

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#145]
For example, in the post: https://pingcap.com/blog/heterogeneous-database-replication-to-tidb

In the table, `DELETE` and `UPDATE` are not displayed in the inline code format.

@YiniXu9506 PTAL

**Comment by std4453** [comment]
As in [here](https://github.com/pingcap/blog/blame/master/heterogeneous-database-replication-to-tidb.md#L136), the markdown file uses a HTML `<table>` instead of the markdown format, so there's no way to support complicated formats with that.

By changing that table to real markdown code, the inline code would work.

```markdown
| **Advantages** | **Disadvantages** |
| -- | -- |
| Your application requires no additional development.<br>CDC tools can obtain all DML changes, like `DELETE` and `UPDATE`.<br>Because the workload is distributed through the day, these tools have higher performance.<br>CDC tools bring low latency and near real-time replication.<br>Upstream data is obtained by reading redo logs, which does not impact the SQL performance. | CDC tools are mostly commercial products, and you need to purchase them.<br>Most CDC tools only allow a specific database as an upstream database. If you have multiple types of upstream databases, you need to use multiple CDC tools. |
```

Certain pitfalls do exist here like a table cell can only occupy one single line, so `<br>` have to be inserted manually and the code looks disgusting.

Another solution is to create these tags manually, like:

```html
<table>
  <tr>
   <td><strong>Advantages</strong>
   </td>
   <td><strong>Disadvantages</strong>
   </td>
  </tr>
  <tr>
   <td>Your application requires no additional development.
<p>
CDC tools can obtain all DML changes, like <code>DELETE</code> and <code>UPDATE</code>.
<p>
Because the workload is distributed through the day, these tools have higher performance.
<p>
CDC tools bring low latency and near real-time replication.
<p>
Upstream data is obtained by reading redo logs, which does not impact the SQL performance.
   </td>
   <td>CDC tools are mostly commercial products, and you need to purchase them.
<p>
Most CDC tools only allow a specific database as an upstream database. If you have multiple types of upstream databases, you need to use multiple CDC tools.
   </td>
  </tr>
</table>
```

So `<code>` tags are inserted manually here. Considering the effort made to write `<table>` tags by hand (which is done in various places throughout the blogs), this should not create too big a trouble.

FYI, here's a list that uses `<table>` tags (from all English blogs):

- 10x-performance-improvement-for-expression-evaluation-made-possible-by-vectorized-execution.md
- 2017-09-08-rocksdbbug.md
- autotikv-tikv-tuning-made-easy-by-machine-learning.md
- doubling-system-read-throughput-with-only-26-lines-of-code.md
- how-tidb-htap-makes-truly-hybrid-workloads-possible.md
- how-we-improved-tpcc-performance-50-percent-and-tpch-performance-100-percent.md
- pessimistic-locking-better-mysql-compatibility-fewer-rollbacks-under-high-load.md
- sql-plan-management-never-worry-about-slow-queries-again.md
- tidb-4.0-ga-gearing-you-up-for-an-unpredictable-world-with-real-time-htap-database.md
- tidb-at-zalopay-infrastructure-lesson-learned.md
- tidb-in-yuanfudao.md
- Time-in-Distributed-Systems.md
- why-we-chose-tidb-over-other-mysql-based-and-newsql-storage-solutions.md
- heterogeneous-database-replication-to-tidb.md

**Comment by CaitinChen** [comment]
@std4453 Thanks.
