### ISSUE TITLE
Change tables from left-justified to center-justified in case studies and blog posts

### ISSUE THREAD

**Issue by CaitinChen** [pingcap/website#146]
For example, in the post: https://pingcap.com/blog/how-tidb-htap-makes-truly-hybrid-workloads-possible

The table is left-justified. Please set all tables to be center-justified.

@YiniXu9506 PTAL

**Comment by std4453** [comment]
The PR above should achieve this.

Meanwhile, the following pages contains long text in table cells, which look strange when center-aligned.

- heterogeneous-database-replication-to-tidb.md
- pessimistic-locking-better-mysql-compatibility-fewer-rollbacks-under-high-load.md

Perhaps you would wish to add `align="left"` to the `<td>` tags to force them to be left-aligned. PTAL. 

The Chinese blogs utilize mostly native markdown tables, where one can specify alignment of each column like:

```markdown
| default | left | center | right |
| ------- | :--- | :----: | ----: |
| a       | b    | c      | d     |
```

Which would be rendered as (by github):

| default | left | center | right |
| --- | :-- | :--: | --: |
| a | b | c | d |

Such format has been used extensively across these blogs and the behavior of the PR above is to respect them (instead of overriding), so only columns with default alignment would be centered. Please check whether that's the expected behavior.

FYI, here's a comprehensive list of files with such tables, from [blog-cn](https://github.com/pingcap/blog-cn):

- 10x-improving-analytical-processing-ability-of-tidb-with-tiflash.md
- 30mins-become-contributor-of-tikv.md
- autotikv.md
- best-practice-haproxy.md
- deployment-by-ansible.md
- dm-source-code-reading-1.md
- dm-source-code-reading-3.md
- dm-source-code-reading-5.md
- dm-source-code-reading-6.md
- dm-source-code-reading-7.md
- dm-source-code-reading-9.md
- dm-source-code-reading-10.md
- fast-pitr-based-on-binlog.md
- how-to-join-in-the-tidb-performance-challenge-program.md
- linearizability.md
- mvcc-in-tikv.md
- reconstruct-built-in-function-report.md
- tidb-4.0-the-leading-real-time-htap-database-is-ready-for-cloud.md
- tidb-and-tiflash-vs-mysql-mariadb-greenplum-apache-spark.md
- tidb-binlog-source-code-reading-4.md
- tidb-source-code-reading-2.md
- tidb-source-code-reading-17.md
- tidb-source-code-reading-22.md
- tikv-source-code-reading-2.md
- tikv-source-code-reading-13.md
- tikv-source-code-reading-16.md
- titan-design-and-implementation.md
- tiup-introduction.md
- unified-thread-pool.md
- use-grafana-to-monitor-and-analyze-tidb-metrics.md
- user-case-beikejinfu.md
- user-case-wangyihuyu.md
- user-case-weiruida.md
- user-case-xiaomi.md

**Comment by CaitinChen** [comment]
@std4453 Sorry. I know how to put the text in the middle of a table cell. Here, I want to put the table in the middle horizontally.

**Comment by std4453** [comment]
@CaitinChen Do you want **ALL** table cells at center, no matter what their headers says, **OR** only those that have not specified their own alignment?
