### ISSUE TITLE
Replace top image with youtube video on TiDB Cloud

### ISSUE THREAD

**Issue by dcalvin** [pingcap/website#203]
Here are the requirements:
1. Embedded  youtube video with sharing supported 
2. Disable video recommendations while pausing or stopping playing. 
3. Full-screen or out of screen play support 
4. Video default screen should be clean without black bar on the upper edge.

![image](https://user-images.githubusercontent.com/2503903/89975678-edbdcc80-dc98-11ea-9f5d-223de80c968e.png)

**Comment by YiniXu9506** [comment]
@dcalvin FYI
The first and third requirements can be satisfied, the second and fourth cannot.

The `ref=0` was used  to hide the recommend videos, however, it is outdated now. We can only display the videos on PingCAP channel. [See more details ](https://developers.google.com/youtube/player_parameters#Revision_History)
![image](https://user-images.githubusercontent.com/34967660/90010511-86bd0980-dcd2-11ea-87e5-d167843a1862.png)

The black fade bar on the upper edge is used to contrast the title of video, share button and more buttons. 
Unfortunately, we cannot hide the info of video because of the para `showInfo` also outdated
![image](https://user-images.githubusercontent.com/34967660/90022002-8a598c00-dce4-11ea-9591-49d7d86ef064.png)

**Comment by dcalvin** [comment]
I think these are acceptable.  Thanks for your effort. We can merge the PR and close this issue.

**Comment by YiniXu9506** [comment]
The video shows on website. PTAL @dcalvin @lilin90

**Comment by lilin90** [comment]
> The video shows on website. PTAL @dcalvin @lilin90

@YiniXu9506 Got it. Thanks a lot!
